version: '3.8'

services:

  postgres_container:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superagent_db
    ports:
      - 5433:5432
    volumes:
      - postgres_data_db:/var/lib/postgresql/data
    networks:
      - superagent-network

  postgres_container_prod:
    image: postgres:13
    container_name: postgres_container_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superagent_db_prod
    ports:
      - 5434:5432
    volumes:
      - postgres_data_prod_db:/var/lib/postgresql/data
    networks:
      - superagent-network

networks:
  superagent-network:
    driver: bridge

volumes:
  postgres_data_db:
  postgres_data_prod_db:
